### ISSUE TITLE
Help me help you...

### ISSUE THREAD

**Issue by i-kocevski** [dkanada/ICEcons#20]
I managed to make an SVG icon for ProtonMail and I'm still pretty much a beginner at making vector graphics but can you tell me more about what resolution should I do the icons in and how can I upload the files to this project and etc. etc.
I think I could do an icon or two a day if I'm in the mood.

Here, check it out (exported this in 256x256):
[Sample icon.zip](https://github.com/dkanada/ICEcons/files/1082018/Sample.icon.zip)

**Comment by conrad-heimbold** [comment]
### How to contribute: 

- If you want to directly contribute more than just two or three icons (or contribute even some code to other projects), I suggest you to learn how to use git (a programm)
- if you only want to contribute two or three icons, then posting the svgs as uploaded file, or in a gist ( https://gist.github.com ) should be enough, no need to learn git. 

## How to style the svgs
- ideal size of the svg would be 048x048 pixel. 
- if it's not that size: no problem, we can scale other sizes up or down to 48x48 px
- the templates for svg files can be found in /templates. If your icon will have a square, rectangular or circle shape; please use one of these templates
- try not to use "transform" elements inside the svgs. 
Unfortunately, Inkscape often adds those without consent. 
If this happens, open XML editor in Inkscape (CTRL SHIFT X), delete the "transform" element and re-position your elements. Other solution: re-position your icon parts by using Object → Transform and **un-check** the "relative positioning" check-mark in the "transform" tab. 

## My personal prefered way of styling svgs in Inkscape
- I am working in 48x48 px documents
- I always make the icon grid visible in inkscape by pressing "#" or View → show icon grid
- I always try to make the icon **fit into the grid as good as possible** This will make the icon **more sharp** if exported to png. 
- I use guide lines heavily. You can transform a normal line (or multiple lines of a form) into a guide line by pressing SHIFT and G. points can be placed more easily, because they snap to those guiding lines. 

You don't have to respect my personal preferred way of styling svgs

**Comment by i-kocevski** [comment]
I will look into git when I have time and thanks for pointing me to those templates, didn't notice them. I hope I can be of some use and contribute to this wonderful project.

**Comment by i-kocevski** [comment]
You told me to learn git but I don't have the permission to push to this repository anyway...
What now? :D

**Comment by conrad-heimbold** [comment]
**Fork it!** :D There is a button for that on the top right corner.

**Comment by conrad-heimbold** [comment]
https://guides.github.com/

**Comment by i-kocevski** [comment]
Oh so yeah... I'm stupid xD Thanks again!
